version: '3.8'

services:
    # PHP service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-php
        environment:
            APP_ENV: ${APP_ENV}
            CONTAINER_ROLE: app
            DB_HOST: database
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - database

    # Database service
    database:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    # phpMyAdmin service
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: laravel-phpmyadmin
        depends_on:
            - database
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8081:80"

volumes:
    db-data:
